### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by luzpaz**
Just some cosmetic tweaks

Edit: I've split the changes to the macro in to 3 [commits](https://github.com/Freedman-CB1/TopoX10/pull/1/commits) for easier review

### CODE REVIEW

**Comment by luzpaz** [comment]
Can we give this macro an icon? If so, it can be added to the header as  `__icon__ = icon_name.svg`

**Comment by Freedman-CB1** [comment]
I will put the icon code in, I have some examples macros from mario52, should I embed the icon in the macro?

**Comment by Freedman-CB1** [comment]
I will put the icon code in.  I have some examples from mario52, should I embed the icon in the macro?

**Comment by luzpaz** [comment]
@chennes can a macro icon be embedded within the macro? I'm assuming as an XPM (i believe so but wasn't certain or sure how)

**Comment by chennes** [comment]
Sure, an XPM can be embedded by using a triple-quoted string, like this:
```
__xpm__ = """/* XPM */
static char * blarg_xpm[] = {
"16 7 2 1",
"* c #000000",
". c #ffffff",
"**..*...........",
"*.*.*...........",
"**..*..**.**..**",
"*.*.*.*.*.*..*.*",
"**..*..**.*...**",
"...............*",
".............**."
};"""
```

**Comment by Freedman-CB1** [comment]
I added the icon text to the header. I gave up on embeding an icon. I added a .svg to the project. I really have no problem giving you my logon name and password if you think it will be easier. I only created this git account for FreeCAD work. I will keep plugging away at what ever you guys want. I don't use the addon manager so it's hard for me know what works. I'm not even sure what your trying to doing. Anyway, thanks

**Comment by luzpaz** [comment]
No need to give me login/pass. You can give me privledges by inviting me to co-manage this specific repository, if you want. Eventually you can learn a little more `git` to use tags/releases instead of creating new macro files each time. git helps with version management and users can see how you evolved the macro over time. Just sayin'

**Pull request merged**
